---
apiVersion: v1
kind: Pod
metadata:
    name: mijenkinsp
    labels:
        app: jenkins
spec:
    containers:
        - name: mijenkinsc
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
#  volumes:
#   - /home/ubuntu/environment/curso/docker/jenkins/data:/var/jenkins_home

#    nodeSelector:
#        tipodisco: ssd

#    nodeName: ip-172-31-31-168

    affinity:
        nodeAffinity:
#            requiredDuringSchedulingIgnoredDuringExecution: 
                # Obliga a que se cumpla lo que definamos para realizar la asignacion
                # Condiciones (Nodo)
#                nodeSelectorTerms:
#                    - matchExpressions:
#                        - key: tipodisco
#                          operator: NotIn # In NotIn Exists DoesNotExists Gt Lt
#                          values:
#                            - hdd
#            preferredDuringSchedulingIgnoredDuringExecution:
                # Preferencia a lo que definamos al realizar la asignacion
                # Condiciones (Nodo)
#                - weight: 10
#                  preference:
#                    matchExpressions:
#                        - key: tipodisco
#                          operator: In # In NotIn Exists DoesNotExists Gt Lt
#                          values:
#                            - hdd            
#                - weight: 5
#                  preference:
#                    matchExpressions:
#                        - key: tipodisco
#                          operator: In # In NotIn Exists DoesNotExists Gt Lt
#                          values:
#                            - cloud     
#        podAffinity:
#            requiredDuringSchedulingIgnoredDuringExecution: 
#                - labelSelector:
#                    - matchExpressions:
#                        - key: app
#                          operator: In # In NotIn Exists DoesNotExists Gt Lt
#                          values:
#                            - nginx
#                  topologyKey: kubernetes.io/hostname # Label que exista en el nodo      
#        podAntiAffinity:
#
#Deployment Kibana (2)<- Afinidad con elasticSearch (topologia: cliente)
#Cluster:
#---
#     Nodo1: label: cliente:1
#     Nodo2: label: cliente:1
#---     
#     Nodo3: label: cliente:2
#            Pod:elasticSearch
#            Pod: Kibana
#---     

#     Nodo4: label: cliente:3
#     Nodo5: label: cliente:3
#            Pod:elasticSearch
#     Nodo6: label: cliente:3
#     Nodo7: label: cliente:3




    
---
apiVersion: v1
kind: Service
metadata:
    name: mijenkinss
spec:
    type: NodePort
    ports:
        - port: 8081
          targetPort: 8080
          nodePort: 30002
    selector:
        app: jenkins