---
apiVersion: v1
kind: Pod
metadata:
    name: mijenkinsp
    labels:
        app: jenkins
spec:
    containers:
        - name: mijenkinsc
          image: jenkins/jenkins:lts
          ports:
            - containerPort: 8080
#  volumes:
#   - /home/ubuntu/environment/curso/docker/jenkins/data:/var/jenkins_home
---
apiVersion: v1
kind: Service
metadata:
    name: mijenkinss
spec:
    ports:
        - port: 8081
          targetPort: 8080
    selector:
        app: jenkins