---
apiVersion: v1
kind: Pod
metadata:
    name: nginx-fedora-p
    labels:
        app: nginx
spec:
    containers:
        - name: nginx-c
          image: nginx
          resources:
            limits:
                cpu: 1
                memory: 1Gi
          ports:
            - containerPort: 80
          volumeMounts:
            - name: compartido
              mountPath: /compartido
        - name: fedora
          image: fedora:latest
          command: ['sh','-c','sleep 3600;']
          volumeMounts:
            - name: compartido
              mountPath: /compartida
            - name: compartido_memoria
              mountPath: /compartida_memoria
            - name: docker
              mountPath: /var/lib/docker
    volumes:
        - name: compartido_memoria
          emptyDir: 
            medium: Memory
            sizeLimit: 1Mi
        - name: compartido
          emptyDir: {}
        - name: docker
          hostPath:
            path: /var/lib/docker
            type: Directory # Es un directorio que debe existir
                    #DirectoryOrCreate # Es un directorio si no existe se debe crear
                    #File # Es un fichero que debe existir
                    #FileOrCreate # Es un fichero si no existe se debe crear

---
apiVersion: v1
kind: Service
metadata:
    name: nginx-fedora-s
spec:
    ports:
        - port: 8082
          targetPort: 80
    selector:
        app: nginx
